"use client";
import {useEffect,useRef,useState} from "react";
import {Upload,ArrowRight,Fuel,FileSpreadsheet,CheckCircle2,AlertTriangle,Send,Code2} from "lucide-react";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {VERSION} from "@/lib/version";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Checkbox} from "@/components/ui/checkbox";
import {selectedReceipts} from "@/lib/selection";
import {Progress} from "@/components/ui/progress";
import {readExcel} from "@/lib/excel";
import {identifier,payload,type SourceRow} from "@/lib/receipts";
type Result={status:string;message:string};
const money=(n:number)=>Number.isFinite(n)?n.toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:4}):"—";
const amount=(n:number)=>Number.isFinite(n)?n.toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2}):"—";
const headers={"Content-Type":"application/json","x-ypf-action":"reviewed"};
export default function Home(){
const [rows,setRows]=useState<SourceRow[]>([]),[filename,setFilename]=useState(""),[loading,setLoading]=useState(false),[error,setError]=useState(""),[configured,setConfigured]=useState(false),[checked,setChecked]=useState(false),[results,setResults]=useState<Record<string,Result>>({}),[sending,setSending]=useState(false),[done,setDone]=useState(0),[detail,setDetail]=useState<SourceRow|null>(null),[confirm,setConfirm]=useState(false);
const [selected,setSelected]=useState<Set<number>>(new Set()),[batchTotal,setBatchTotal]=useState(0);
const stop=useRef(false),busy=useRef(false);
useEffect(()=>{fetch("/api/status",{cache:"no-store"}).then(r=>r.json() as Promise<{configured:boolean}>).then(d=>setConfigured(d.configured)).catch(()=>setError("No se pudo comprobar la conexión del portal."));},[]);
const ready=rows.filter(r=>!r.errors.length&&!results[identifier(r)]);
const selectedReady=selectedReceipts(rows,selected,results);
const allSelected=ready.length>0&&selectedReady.length===ready.length;
function toggleRow(row:number,value:boolean){setSelected(old=>{const next=new Set(old);if(value)next.add(row);else next.delete(row);return next;});}
function clearWorkspace(){setRows([]);setFilename("");setError("");setChecked(false);setResults({});setSelected(new Set());setDone(0);setBatchTotal(0);setDetail(null);setConfirm(false);stop.current=false;}
const invalid=rows.filter(r=>r.errors.length).length;
const sent=Object.values(results).filter(r=>r.status==="sent").length;
async function load(file:File|undefined){if(!file||busy.current)return;clearWorkspace();setFilename(file.name);if(!file.name.toLowerCase().endsWith(".xlsx")){setError("Seleccioná un archivo Excel .xlsx.");return;}if(file.size>10*1024*1024){setError("El archivo supera el máximo de 10 MB.");return;}setLoading(true);try{const data=await readExcel(await file.arrayBuffer());setRows(data);setChecked(true);}catch(e){setError(e instanceof Error?e.message:"No se pudo leer el archivo.");}finally{setLoading(false);}}
async function send(){if(busy.current||!checked||!configured||!selectedReady.length)return;const batch=[...selectedReady];setBatchTotal(batch.length);busy.current=true;stop.current=false;setConfirm(false);setSending(true);setDone(0);setError("");let count=0;try{for(const row of batch){if(stop.current)break;let body:Result & {error?:string};try{const response=await fetch("/api/send",{method:"POST",headers,body:JSON.stringify(row)});body=await response.json() as Result & {error?:string};if(body.error){setError(body.error+" El lote se detuvo.");break;}if(!body.status)throw new Error("Formato no reconocido");}catch(error){body={status:"uncertain",message:"No se pudo leer la respuesta del portal: "+(error instanceof Error?error.message:"sin detalle")};stop.current=true;}setResults(old=>({...old,[identifier(row)]:body}));setDone(++count);if(body.status!=="sent"){setError(body.message+" El lote se detuvo para revisar este resultado.");break;}}}finally{busy.current=false;setSending(false);}}
useEffect(()=>{if(!sending)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[sending]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:"inspect_receipt_preview",title:"Consultar previsualización",description:"Devuelve el estado de la revisión y el JSON de una fila cargada. No envía documentos.",inputSchema:{type:"object",properties:{row:{type:"integer",minimum:2}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const x=input as {row?:number};if(!x||typeof x!=="object"||Object.keys(x).some(k=>k!=="row")||(x.row!==undefined&&(!Number.isInteger(x.row)||x.row<2)))throw new Error("Fila inválida");if(x.row!==undefined){const r=rows.find(r=>r.row===x.row);if(!r)throw new Error("Fila no encontrada");return {row:r.row,errors:r.errors,payload:r.errors.length?null:payload(r)};}return {file:filename,rows:rows.length,ready:ready.length,selected:selectedReady.length,invalid,sent,sending};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[rows,filename,ready.length,selectedReady.length,invalid,sent,sending]);
return <main className="workspace">
<header className="topbar"><span className="brand"><Fuel size={22}/> YPF EN RUTA</span><span className="muted">Importación a Finnegans <span className="private">Acceso privado</span><span className="private">v{VERSION}</span></span></header>
<div className="heading"><p className="eyebrow">RECEPCIONES DE COMPRA</p><h1>Revisá tus consumos.<br/><span>Después, enviá.</span></h1><p>Una fila del Excel, una recepción. Revisá los datos antes de confirmar el envío.</p></div>
<section className={"panel upload "+(rows.length?"compact":"")}><Upload size={30}/><div><h2>{filename||"Cargá el archivo de consumos"}</h2><p>{loading?"Leyendo y verificando recepciones…":"Excel .xlsx · Hoja FINAL · Hasta 10 MB"}</p></div><label className={"primary "+(loading||sending?"disabled":"")}>{rows.length?"Cambiar archivo":"Seleccionar archivo"}<ArrowRight size={18}/><input aria-label="Seleccionar archivo Excel" type="file" accept=".xlsx" disabled={loading||sending} onChange={e=>{void load(e.target.files?.[0]);e.target.value="";}}/></label></section>
<div className="steps"><span className={!rows.length?"active":""}>01 Seleccionar Excel</span><span className={rows.length&&!sent?"active":""}>02 Revisar recepciones</span><span className={sent?"active":""}>03 Enviar a Finnegans</span></div>
{error&&<div className="notice error" role="alert"><AlertTriangle size={20}/>{error}</div>}
{rows.length>0&&<><section className="summary panel"><div><span>Recepciones</span><strong>{rows.length}</strong></div><div><span>Listas para enviar</span><strong>{ready.length}</strong></div><div><span>Con observaciones</span><strong>{invalid}</strong></div><div><span>Enviadas</span><strong>{sent}</strong></div><div><span>Neto del archivo</span><strong>$ {amount(rows.reduce((s,r)=>s+(Number.isFinite(r.net)?r.net:0),0))}</strong></div></section>
<div className="rules"><span>Empresa <b>049CDS</b></span><span>Documento <b>YPF-R</b></span><span>Producto <b>62</b></span><span>DIMCTC <b>1160</b></span><span>SUCDES <b>014CDS</b></span></div>
{invalid>0&&<div className="notice"><AlertTriangle size={20}/>{invalid} filas requieren revisión y quedarán excluidas del envío. Consultá el detalle de cada fila.</div>}
<section className="panel data"><div className="section-title"><div><h2><FileSpreadsheet size={20}/> Previsualización</h2><p className="muted">Precio con signo negativo · Distribuciones al 100 % del neto</p></div><span className="muted">Hoja FINAL</span></div><div className="table-scroll"><Table><TableHeader><TableRow><TableHead><Checkbox aria-label="Seleccionar todas las recepciones listas" checked={allSelected} indeterminate={selectedReady.length>0&&!allSelected} disabled={sending||loading||!checked||!ready.length} onCheckedChange={value=>setSelected(value?new Set(ready.map(r=>r.row)):new Set())}/></TableHead>{["Estado","Fecha / hora","Tarjeta / Patente","Proveedor SAP","Razón social","Factura","Litros","Precio","Neto","JSON a enviar"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=>{const result=results[identifier(r)];return <TableRow key={r.row} data-state={selected.has(r.row)&&!r.errors.length&&!result?"selected":undefined}><TableCell><Checkbox aria-label={"Seleccionar recepción de fila "+r.row} checked={selected.has(r.row)&&!r.errors.length&&!result} disabled={sending||loading||!checked||!!r.errors.length||!!result} onCheckedChange={value=>toggleRow(r.row,value)}/></TableCell><TableCell>{result?<button type="button" className={"status grid-action "+(result.status==="sent"?"ok":"bad")} onClick={()=>setDetail(r)} title={result.message}>{result.status==="sent"?"Enviada · Ver respuesta":"Error · Ver respuesta"}</button>:<span className={"status "+(r.errors.length?"bad":"")}>{r.errors.length?"Revisar":"Lista"}</span>}</TableCell><TableCell><span>{r.date||"—"}</span><span className="card-number">{r.time||"—"}</span></TableCell><TableCell><span className="card-number">{r.card}</span><strong className="plate">{r.plate}</strong></TableCell><TableCell>{r.sap||"—"}</TableCell><TableCell className="business-name">{r.businessName||"—"}</TableCell><TableCell>{r.invoice||"—"}</TableCell><TableCell className="number">{money(r.quantity)}</TableCell><TableCell className="number">{amount(-r.price)}</TableCell><TableCell className="number">{amount(r.net)}</TableCell><TableCell><button type="button" className="status grid-action" onClick={()=>setDetail(r)} aria-label={"Previsualizar JSON de la fila "+r.row}><Code2 size={15}/>Ver JSON</button></TableCell></TableRow>;})}</TableBody></Table></div></section>
<div className="sendbar panel"><div><strong>{sending?"Enviando recepciones…":selectedReady.length+" recepciones seleccionadas"}</strong><p className="muted">{sending?done+" respuestas recibidas en este lote":"Marcá las recepciones que querés enviar. Solo se enviarán las seleccionadas."}</p>{sending&&<Progress aria-label="Progreso de envío" value={done/Math.max(batchTotal,1)*100}/>}</div>{sending?<button className="secondary" onClick={()=>{stop.current=true;setError("Se detendrá al finalizar la recepción en curso.");}}>Detener después de esta recepción</button>:<button className="primary" disabled={!selectedReady.length||!configured||!checked||loading} onClick={()=>setConfirm(true)}><Send size={18}/>Enviar a Finnegans</button>}</div>
{!configured&&<p className="notice">El envío estará disponible cuando estén configuradas las credenciales de Finnegans.</p>}
</>}
{!rows.length&&!loading&&<div className="empty-info"><CheckCircle2 size={18}/><span>El archivo se lee para previsualizar. El envío comienza únicamente cuando lo confirmás.</span></div>}
<Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null);}}><DialogContent className="receipt-dialog"><DialogTitle>JSON a enviar · Fila {detail?.row}</DialogTitle><DialogDescription>{detail?.businessName||"Sin razón social"} · {detail?.product} · {detail?.plate}</DialogDescription>{detail&&<>{detail.errors.length?<p className="notice error"><AlertTriangle size={20}/>No se puede generar el JSON de esta fila hasta resolver sus observaciones.</p>:<p className="notice json-message"><CheckCircle2 size={20}/>Esta es la previsualización exacta del JSON que se enviará a Finnegans si seleccionás esta recepción y confirmás el envío.</p>}{detail.errors.map(e=><p className="notice error" key={e}>{e}</p>)}{results[identifier(detail)]&&<div className={"api-message "+(results[identifier(detail)].status==="sent"?"success":"failure")}><strong>Respuesta de Finnegans</strong><span>{results[identifier(detail)].message}</span></div>}{!detail.errors.length&&<pre id={"json-fila-"+detail.row}>{JSON.stringify(payload(detail),null,2)}</pre>}</>}</DialogContent></Dialog>
<Dialog open={confirm} onOpenChange={setConfirm}><DialogContent className="confirm-dialog"><DialogTitle>Enviar {selectedReady.length} recepciones seleccionadas</DialogTitle><DialogDescription>Se crearán documentos YPF-R en Finnegans para la empresa 049CDS. Solo las filas seleccionadas se enviarán, cada una por separado.</DialogDescription><p>Neto a enviar: <strong>$ {amount(selectedReady.reduce((sum,r)=>sum+r.net,0))}</strong></p><div className="actions"><button className="secondary" onClick={()=>setConfirm(false)}>Volver a revisar</button><button className="primary" onClick={()=>void send()}>Confirmar envío</button></div></DialogContent></Dialog>
</main>;}
