"use client";
import {useEffect,useRef,useState} from "react";
import {Fuel,Upload,FileUp,RotateCw,ChevronRight,SlidersHorizontal,Grid3x3,XCircle,CheckCircle2,AlertTriangle,Send,Code2} from "lucide-react";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {VERSION} from "@/lib/version";
import {FinModal,MessageModal,type Message} from "@/components/fin-modal";
import {Checkbox} from "@/components/ui/checkbox";
import {selectedReceipts} from "@/lib/selection";
import {Progress} from "@/components/ui/progress";
import {readExcel} from "@/lib/excel";
import {identifier,payload,validSucdes,DEFAULT_EMPRESA,type SourceRow} from "@/lib/receipts";
import {matchBranch,type Branch} from "@/lib/branches";
import {BranchSelect} from "@/components/branch-select";
type Result={status:string;message:string};
const money=(n:number)=>Number.isFinite(n)?n.toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:4}):"—";
const amount=(n:number)=>Number.isFinite(n)?n.toLocaleString("es-AR",{minimumFractionDigits:2,maximumFractionDigits:2}):"—";
const headers={"Content-Type":"application/json","x-ypf-action":"reviewed"};
// Fills sucdes from the Excel "Sucursal" column; rows without a match get "" and must be chosen by hand.
function assignBranches(rows:SourceRow[],branches:Branch[]){let unmatched=0;const cache=new Map<string,string>();const next=rows.map(r=>{if(r.sucdes!==undefined)return r;const key=r.branch??"";if(!cache.has(key))cache.set(key,matchBranch(key,branches)?.code??"");const code=cache.get(key)!;if(!code&&!r.errors.length)unmatched++;return {...r,sucdes:code};});return {rows:next,unmatched};}
const autoSelected=(rows:SourceRow[])=>rows.filter(r=>!r.errors.length&&validSucdes(r.sucdes)).map(r=>r.row);
function unmatchedText(rows:SourceRow[],unmatched:number){const names=[...new Set(rows.filter(r=>!r.errors.length&&!r.sucdes).map(r=>r.branch||"(vacía)"))];return unmatched+" filas no tienen una sucursal de Finnegans que coincida con el Excel ("+names.join(", ")+"). Elegila en la columna Sucursal de la grilla; hasta entonces no se pueden enviar.";}
export default function Home(){
const [rows,setRows]=useState<SourceRow[]>([]),[filename,setFilename]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState<Message|null>(null),[stopping,setStopping]=useState(false),[configured,setConfigured]=useState(false),[checked,setChecked]=useState(false),[results,setResults]=useState<Record<string,Result>>({}),[sending,setSending]=useState(false),[done,setDone]=useState(0),[detail,setDetail]=useState<SourceRow|null>(null),[confirm,setConfirm]=useState(false);
const [selected,setSelected]=useState<Set<number>>(new Set()),[batchTotal,setBatchTotal]=useState(0),[branches,setBranches]=useState<Branch[]|null>(null),[branchError,setBranchError]=useState(""),[empresa,setEmpresa]=useState(DEFAULT_EMPRESA);
const stop=useRef(false),busy=useRef(false);
const notify=(kind:Message["kind"],title:string,text:string,detail?:string)=>setMessage({kind,title,text,detail});
useEffect(()=>{fetch("/api/status",{cache:"no-store"}).then(r=>r.json() as Promise<{configured:boolean}>).then(d=>{setConfigured(d.configured);if(!d.configured)notify("warning","Credenciales no configuradas","El envío estará disponible cuando estén configuradas las credenciales de Finnegans. Podés cargar y revisar el archivo igualmente.");}).catch(()=>notify("error","Sin conexión","No se pudo comprobar la conexión del portal. Recargá la página e intentá nuevamente."));
fetch("/api/branches",{cache:"no-store"}).then(r=>r.json() as Promise<{branches?:Branch[];error?:string}>).then(d=>{if(!d.branches)throw new Error(d.error||"Respuesta sin sucursales");setBranches(d.branches);}).catch(e=>{const text=e instanceof Error?e.message:"sin detalle";setBranchError(text);setBranches([]);notify("error","No se pudieron obtener las sucursales","Sin la lista de sucursales de Finnegans no se puede completar la dimensión SUCDES y las filas no se podrán enviar. Recargá la página para reintentar.",text);});},[]);
// Auto-match the Excel "Sucursal" once the branch list is available (rows loaded before the list arrives are matched here).
useEffect(()=>{if(!branches?.length||!rows.some(r=>r.sucdes===undefined))return;const {rows:next,unmatched}=assignBranches(rows,branches);const fresh=new Set(rows.filter(r=>r.sucdes===undefined).map(r=>r.row));setRows(next);setSelected(old=>new Set([...old,...autoSelected(next).filter(row=>fresh.has(row))]));if(unmatched)notify("warning","Filas sin sucursal",unmatchedText(next,unmatched));},[branches,rows]);
const ready=rows.filter(r=>!r.errors.length&&validSucdes(r.sucdes)&&!results[identifier(r)]);
const noBranch=rows.filter(r=>!r.errors.length&&!validSucdes(r.sucdes)&&!results[identifier(r)]).length;
const branchCounts=new Map<string,number>();rows.forEach(r=>{if(!results[identifier(r)])branchCounts.set(r.branch??"",(branchCounts.get(r.branch??"")??0)+1);});
function setBranch(target:SourceRow,code:string,applyToSame:boolean){setRows(old=>old.map(r=>r.row===target.row||(applyToSame&&(r.branch??"")===(target.branch??"")&&!results[identifier(r)])?{...r,sucdes:code}:r));}
const selectedReady=selectedReceipts(rows,selected,results);
const allSelected=ready.length>0&&selectedReady.length===ready.length;
function toggleRow(row:number,value:boolean){setSelected(old=>{const next=new Set(old);if(value)next.add(row);else next.delete(row);return next;});}
function clearWorkspace(){setRows([]);setFilename("");setChecked(false);setResults({});setSelected(new Set());setDone(0);setBatchTotal(0);setDetail(null);setConfirm(false);stop.current=false;}
const invalid=rows.filter(r=>r.errors.length).length;
const sent=Object.values(results).filter(r=>r.status==="sent").length;
async function load(file:File|undefined){if(!file||busy.current)return;clearWorkspace();setFilename(file.name);if(!file.name.toLowerCase().endsWith(".xlsx")){notify("error","Archivo no válido","Seleccioná un archivo Excel con extensión .xlsx.");return;}if(file.size>10*1024*1024){notify("error","Archivo no válido","El archivo supera el máximo de 10 MB.");return;}setLoading(true);try{let data=await readExcel(await file.arrayBuffer());let unmatched=0;if(branches?.length)({rows:data,unmatched}=assignBranches(data,branches));setRows(data);setSelected(new Set(autoSelected(data)));setChecked(true);const bad=data.filter(r=>r.errors.length).length;const notes=[bad?bad+" de "+data.length+" filas requieren revisión y quedarán excluidas del envío. Consultá el detalle de cada fila con \"Ver JSON\".":"",unmatched?unmatchedText(data,unmatched):""].filter(Boolean);if(notes.length)notify("warning",bad&&unmatched?"Revisá el archivo":bad?"Filas con observaciones":"Filas sin sucursal",notes.join(" "));}catch(e){notify("error","No se pudo leer el archivo",e instanceof Error?e.message:"No se pudo leer el archivo.");}finally{setLoading(false);}}
async function send(){if(busy.current||!checked||!configured||!selectedReady.length)return;const batch=[...selectedReady];setBatchTotal(batch.length);busy.current=true;stop.current=false;setConfirm(false);setSending(true);setStopping(false);setDone(0);let count=0;const ok:SourceRow[]=[],failed:{row:SourceRow;result:Result}[]=[];let halt:string|null=null;try{for(const row of batch){if(stop.current)break;let body:Result&{error?:string};try{const response=await fetch("/api/send",{method:"POST",headers,body:JSON.stringify({...row,empresa})});body=await response.json() as Result&{error?:string};if(body.error){if(response.status!==400){halt=body.error;break;}body={status:"failed",message:body.error};}else if(!body.status)throw new Error("Formato no reconocido");}catch(error){body={status:"uncertain",message:"No se pudo leer la respuesta del portal: "+(error instanceof Error?error.message:"sin detalle")};}setResults(old=>({...old,[identifier(row)]:body}));setDone(++count);if(body.status==="sent")ok.push(row);else failed.push({row,result:body});}}finally{busy.current=false;setSending(false);setStopping(false);}
const pending=batch.length-ok.length-failed.length;const errors=failed.map(f=>"Fila "+f.row.row+" · "+(f.result.status==="uncertain"?"Incierto":"Rechazada")+": "+f.result.message).join("\n");
const summary="Se enviaron "+ok.length+" de "+batch.length+" recepciones."+(failed.length?" "+failed.length+" con error: revisalas en la grilla con \"Ver respuesta\".":"")+(pending?" "+pending+" quedaron sin enviar y siguen seleccionadas.":"");
if(halt)notify("error","Envío detenido",halt+" "+summary,errors||undefined);
else if(!failed.length&&!pending)notify("success","Envío finalizado","Se enviaron "+ok.length+" recepciones a Finnegans correctamente.");
else if(!failed.length)notify("info","Envío detenido",summary);
else notify(ok.length?"warning":"error",ok.length?"Envío finalizado con errores":"Ninguna recepción fue aceptada",summary,errors);}
useEffect(()=>{if(!sending)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[sending]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:"inspect_receipt_preview",title:"Consultar previsualización",description:"Devuelve el estado de la revisión y el JSON de una fila cargada. No envía documentos.",inputSchema:{type:"object",properties:{row:{type:"integer",minimum:2}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const x=input as {row?:number};if(!x||typeof x!=="object"||Object.keys(x).some(k=>k!=="row")||(x.row!==undefined&&(!Number.isInteger(x.row)||x.row<2)))throw new Error("Fila inválida");if(x.row!==undefined){const r=rows.find(r=>r.row===x.row);if(!r)throw new Error("Fila no encontrada");return {row:r.row,errors:r.errors,payload:r.errors.length||!validSucdes(r.sucdes)?null:payload({...r,empresa})};}return {file:filename,rows:rows.length,ready:ready.length,selected:selectedReady.length,invalid,sent,sending};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[rows,filename,ready.length,selectedReady.length,invalid,sent,sending,empresa]);
const net=rows.reduce((s,r)=>s+(Number.isFinite(r.net)?r.net:0),0);
const step=sent?3:rows.length?2:1;
return <div className="app">

<main className="workspace">
<div className="view-title"><Fuel className="view-icon" size={22}/><h1>Recepciones - YPF en ruta</h1><button type="button" className="round-icon" title="Limpiar y empezar de nuevo" aria-label="Limpiar y empezar de nuevo" disabled={sending||loading} onClick={clearWorkspace}><RotateCw size={14}/></button><span className="view-version">v{VERSION}</span></div>
<div className="params"><span className="params-label"><SlidersHorizontal size={15}/> Parámetros <ChevronRight size={14}/></span><span className="pill"><small>Archivo</small>{filename||"Sin archivo"}</span><span className="pill pill-select"><small>Empresa</small>{branches?.length?<BranchSelect className="in-pill" value={empresa} branches={branches} disabled={sending} sameCount={1} placeholder="Elegir empresa" searchLabel="Buscar empresa o código…" onChange={code=>setEmpresa(code)}/>:empresa}</span></div>
<nav className="tabs" aria-label="Pasos"><span className={step===1?"active":""}>Seleccionar Excel</span><span className={step===2?"active":""}>Revisar recepciones</span><span className={step===3?"active":""}>Enviar a Finnegans</span></nav>
<div className="toolbar"><label className={"tool "+(loading||sending?"disabled":"")}><FileUp size={15}/>{rows.length?"Cambiar Excel":"Cargar Excel"}<input aria-label="Seleccionar archivo Excel" type="file" accept=".xlsx" disabled={loading||sending} onChange={e=>{void load(e.target.files?.[0]);e.target.value="";}}/></label><button type="button" className="tool" disabled={!selectedReady.length||!configured||!checked||loading||sending} onClick={()=>setConfirm(true)}><Send size={15}/>Enviar a Finnegans</button><button type="button" className="tool" disabled={!rows.length||sending||loading} onClick={clearWorkspace}><XCircle size={15}/>Limpiar</button>
{rows.length>0&&<div className="counters"><span>Recepciones <b>{rows.length}</b></span><span>Listas <b>{ready.length}</b></span><span>Observaciones <b className={invalid?"warn":""}>{invalid}</b></span><span>Sin sucursal <b className={noBranch?"warn":""}>{noBranch}</b></span><span>Enviadas <b className={sent?"good":""}>{sent}</b></span><span>Neto <b>$ {amount(net)}</b></span></div>}</div>
{!rows.length&&<label className={"dropzone "+(loading?"disabled":"")}><Upload size={28}/><strong>{loading?"Leyendo y verificando recepciones…":filename||"Cargá el archivo de consumos"}</strong><span>Excel .xlsx · Hoja FINAL · Hasta 10 MB. El archivo se lee para previsualizar; el envío comienza únicamente cuando lo confirmás.</span><span className="gradient">Seleccionar archivo</span><input aria-label="Seleccionar archivo Excel" type="file" accept=".xlsx" disabled={loading||sending} onChange={e=>{void load(e.target.files?.[0]);e.target.value="";}}/></label>}
{rows.length>0&&<>
<section className="grid"><div className="grid-caption"><Grid3x3 size={14}/> Documento: YPF en Ruta · Precio con signo negativo · Distribuciones al 100 % del neto</div><div className="table-scroll"><Table><TableHeader><TableRow><TableHead><Checkbox aria-label="Seleccionar todas las recepciones listas" checked={allSelected} indeterminate={selectedReady.length>0&&!allSelected} disabled={sending||loading||!checked||!ready.length} onCheckedChange={value=>setSelected(value?new Set(ready.map(r=>r.row)):new Set())}/></TableHead>{["Estado","Fecha / hora","Tarjeta / Patente","Proveedor SAP","Razón social","Sucursal (SUCDES)","Factura","Litros","Precio","Neto","JSON a enviar"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=>{const result=results[identifier(r)];return <TableRow key={r.row} data-state={selected.has(r.row)&&!r.errors.length&&validSucdes(r.sucdes)&&!result?"selected":undefined}><TableCell><Checkbox aria-label={"Seleccionar recepción de fila "+r.row} checked={selected.has(r.row)&&!r.errors.length&&validSucdes(r.sucdes)&&!result} disabled={sending||loading||!checked||!!r.errors.length||!validSucdes(r.sucdes)||!!result} title={!r.errors.length&&!validSucdes(r.sucdes)?"Elegí una sucursal para poder enviar esta fila":undefined} onCheckedChange={value=>toggleRow(r.row,value)}/></TableCell><TableCell>{result?<button type="button" className={"status grid-action "+(result.status==="sent"?"ok":"bad")} onClick={()=>setDetail(r)} title={result.message}>{result.status==="sent"?"Enviada · Ver respuesta":"Error · Ver respuesta"}</button>:<span className={"status "+(r.errors.length||!validSucdes(r.sucdes)?"bad":"")}>{r.errors.length?"Revisar":validSucdes(r.sucdes)?"Lista":"Sin sucursal"}</span>}</TableCell><TableCell><span>{r.date||"—"}</span><span className="card-number">{r.time||"—"}</span></TableCell><TableCell><span className="card-number">{r.card}</span><strong className="plate">{r.plate}</strong></TableCell><TableCell>{r.sap||"—"}</TableCell><TableCell className="business-name">{r.businessName||"—"}</TableCell><TableCell className="branch-cell"><span className="card-number">{r.branch||"Sin sucursal en Excel"}</span>{branches===null?<span className="muted">Cargando sucursales…</span>:branchError?<span className="status bad">Sin lista de sucursales</span>:<BranchSelect value={r.sucdes} branches={branches} excel={r.branch} disabled={sending||loading||!!result} sameCount={branchCounts.get(r.branch??"")??1} onChange={(code,same)=>setBranch(r,code,same)}/>}</TableCell><TableCell>{r.invoice||"—"}</TableCell><TableCell className="number">{money(r.quantity)}</TableCell><TableCell className="number">{amount(-r.price)}</TableCell><TableCell className="number">{amount(r.net)}</TableCell><TableCell><button type="button" className="link-action" onClick={()=>setDetail(r)} aria-label={"Previsualizar JSON de la fila "+r.row}><Code2 size={14}/>Ver JSON</button></TableCell></TableRow>;})}</TableBody></Table></div></section>
<div className="sendbar"><div><strong>{sending?"Enviando recepciones…":selectedReady.length+" recepciones seleccionadas"}</strong><p className="muted">{sending?done+" respuestas recibidas en este lote":"Marcá las recepciones que querés enviar. Solo se enviarán las seleccionadas."}</p>{sending&&<Progress aria-label="Progreso de envío" value={done/Math.max(batchTotal,1)*100}/>}</div>{sending?<button className="secondary" disabled={stopping} onClick={()=>{stop.current=true;setStopping(true);}}>{stopping?"Deteniendo al finalizar la recepción en curso…":"Detener después de esta recepción"}</button>:<button className="gradient" disabled={!selectedReady.length||!configured||!checked||loading} onClick={()=>setConfirm(true)}><Send size={16}/>Enviar a Finnegans</button>}</div>
</>}
</main>
<FinModal open={!!detail} onClose={()=>setDetail(null)} size="lg" title={"JSON a enviar · Fila "+(detail?.row??"")} subtitle={detail?(detail.businessName||"Sin razón social")+" · "+detail.product+" · "+detail.plate:undefined} footer={<button type="button" className="fin-primary" onClick={()=>setDetail(null)}>Cerrar</button>}>{detail&&<>{!detail.errors.length&&!validSucdes(detail.sucdes)?<p className="notice"><AlertTriangle size={18}/>Elegí la sucursal (SUCDES) de esta fila en la grilla para generar el JSON.</p>:detail.errors.length?<p className="notice error"><AlertTriangle size={18}/>No se puede generar el JSON de esta fila hasta resolver sus observaciones.</p>:<p className="notice json-message"><CheckCircle2 size={18}/>Esta es la previsualización exacta del JSON que se enviará a Finnegans si seleccionás esta recepción y confirmás el envío.</p>}{detail.errors.map(e=><p className="notice error" key={e}>{e}</p>)}{results[identifier(detail)]&&<div className={"api-message "+(results[identifier(detail)].status==="sent"?"success":"failure")}><strong>Respuesta de Finnegans</strong><span>{results[identifier(detail)].message}</span></div>}{!detail.errors.length&&validSucdes(detail.sucdes)&&<pre className="json-preview" id={"json-fila-"+detail.row}>{JSON.stringify(payload({...detail,empresa}),null,2)}</pre>}</>}</FinModal>
<FinModal open={confirm} onClose={()=>setConfirm(false)} title={"Enviar "+selectedReady.length+" recepciones seleccionadas"} footer={<><button type="button" className="fin-secondary" onClick={()=>setConfirm(false)}>Volver a revisar</button><button type="button" className="fin-primary" onClick={()=>void send()}>Confirmar envío</button></>}><p>Se crearán documentos <b>YPF-R</b> en Finnegans para la empresa <b>{empresa}</b>. Solo las filas seleccionadas se enviarán, cada una por separado y con la sucursal (SUCDES) elegida en la grilla.</p><div className="fin-field"><span>Neto a enviar</span><strong>$ {amount(selectedReady.reduce((sum,r)=>sum+r.net,0))}</strong></div></FinModal>
<MessageModal message={message} onClose={()=>setMessage(null)}/>
</div>;}
